In [1]:
'''
## Agenda for the Notebook

1. Initializing Tensors
    
    <ol>1.1 Initializing 1D tensor</ol>

    <ol>1.2 Initializing 2D tensor</ol>

    <ol>1.3 Initializing 3D tensor</ol>

    <ol>1.4 Randomly initializing tensors</ol>

2. Mathematical Operations in PyTorch

3. Matrix Operations in PyTorch
    
    <ol>3.1 Matrix addition</ol>

    <ol>3.2 Matrix subtraction</ol>

    <ol>3.3 Matrix multiplication</ol>

    <ol>3.4 Matrix division</ol>

    <ol>3.5 Transpose of a matrix</ol>

    <ol>3.6 Reshaping 2d tensors</ol>

4. Converting NumPy arrays to PyTorch Tensors

4. Converting PyTorch Tensors to NumPy array

4. Using tensor on GPU
'''

'\n## Agenda for the Notebook\n\n1. Initializing Tensors\n    \n    <ol>1.1 Initializing 1D tensor</ol>\n\n    <ol>1.2 Initializing 2D tensor</ol>\n\n    <ol>1.3 Initializing 3D tensor</ol>\n\n    <ol>1.4 Randomly initializing tensors</ol>\n\n2. Mathematical Operations in PyTorch\n\n3. Matrix Operations in PyTorch\n    \n    <ol>3.1 Matrix addition</ol>\n\n    <ol>3.2 Matrix subtraction</ol>\n\n    <ol>3.3 Matrix multiplication</ol>\n\n    <ol>3.4 Matrix division</ol>\n\n    <ol>3.5 Transpose of a matrix</ol>\n\n    <ol>3.6 Reshaping 2d tensors</ol>\n\n4. Converting NumPy arrays to PyTorch Tensors\n\n4. Converting PyTorch Tensors to NumPy array\n\n4. Using tensor on GPU\n'

In [3]:
## 1. Initializing Tensors
# importing PyTorch library and checking its version
!pip install torch torchvision torchaudio

import torch
print(torch.__version__)

  Using cached filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 MB 893.9 kB/s eta 0:00:00m eta 0:00:010:00:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 859.7 kB/s eta 0:00:000:00:01m eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 875.6 kB/s eta 0:00:000:00:01m eta 0:00:01
Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 1.2 MB/s eta 0:00:001.2 MB/s eta 0:00:01
Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
2.2.0


In [4]:
### 1.1 Initializing a 1D tensor

In [5]:
# initializing a 1D tensor
one_d_tensor = torch.tensor([1])
print(one_d_tensor)

tensor([1])


In [6]:
# shape of 1d tensor
one_d_tensor.shape

torch.Size([1])

In [8]:
### 1.2 Initializing 2D tensor
# initializing a 1D tensor
two_d_tensor = torch.tensor([[1, 2], [3, 4]])
print(two_d_tensor)

tensor([[1, 2],
        [3, 4]])


In [9]:
# shape of 2d tensor
two_d_tensor.shape

torch.Size([2, 2])

In [10]:
# initializing a 1D tensor
three_d_tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                               [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(three_d_tensor)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])


In [11]:
# shape of 3d tensor
three_d_tensor.shape

torch.Size([2, 3, 3])

In [12]:
### 1.4 Randomly initializing tensors

In [13]:
# setting the random seed for PyTorch
# torch.manual_seed(42)
# 1d tensor of random numbers
random_1d_tensor = torch.randn(3)
random_1d_tensor

tensor([ 0.6730, -0.6151,  0.9861])

In [14]:
# setting the random seed for PyTorch
torch.manual_seed(42)
# 2d tensor of random numbers
random_2d_tensor = torch.randn(3,3)
random_2d_tensor

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [15]:
# setting the random seed for PyTorch
torch.manual_seed(42)
# 3d tensor of random numbers
random_3d_tensor = torch.randn(2,3,3)
random_3d_tensor

tensor([[[ 1.9269,  1.4873, -0.4974],
         [ 0.4396, -0.7581,  1.0783],
         [ 0.8008,  1.6806,  0.3559]],

        [[-0.6866,  0.6105,  1.3347],
         [-0.2316,  0.0418, -0.2516],
         [ 0.8599, -0.3097, -0.3957]]])

In [16]:
## 2. Mathematical Operations in PyTorch
# initializing two tensors
a = torch.tensor(2)
b = torch.tensor(1)
print(a,b)

tensor(2) tensor(1)


In [17]:
# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

tensor(3)
tensor(-1)
tensor(2)
tensor(2.)


In [18]:
## 3. Matrix Operations in PyTorch
# setting the random seed for pytorch and initializing two 2d tensors
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)

In [19]:
# printing first matrix
print(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


In [20]:
# printing second matrix
print(b)

tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])


In [21]:
### 3.1 Matrix addition

In [22]:
# adding two matrices using torch.add
addition = torch.add(a,b)
print(addition)

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])


In [23]:
### 3.2 Matrix subtraction

In [24]:
# subtracting one matrix from the other using torch.sub
subtraction = torch.sub(a,b)
print(subtraction)

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])


In [25]:
### 3.3 Matrix Multiplication

In [26]:
# matrix multiplication using torch.mm
# this is similar to dot product

dot_product = torch.mm(a,b)
print(dot_product)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])


In [27]:
# matrix multiplication using torch.matmul

matrix_multiplication = torch.matmul(a,b)
print(matrix_multiplication)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])


In [28]:
# matrix multiplication using torch.mul
# this performs elementwise multiplication

elementwise_multiplication = torch.mul(a,b)
print(elementwise_multiplication)

tensor([[ 0.0900,  0.0689,  0.1898],
        [ 0.2557,  1.8974,  0.1843],
        [ 2.1154, -0.8435,  0.3773]])


In [29]:
### 3.4 Matrix division

In [30]:
# dividing one matrix by the other using torch.div
division = torch.div(a,b)
print(division)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [31]:
### 3.5 Transpose of a matrix
# calculating the transpose of a 2d tensor in PyTorch
# original matrix
print(a, '\n')

# matrix transpose
torch.t(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 



tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])

In [32]:
### 3.6 Reshaping 2d tensors
# setting the random seed for pytorch
torch.manual_seed(42)

# initializing tensor
a = torch.randn(2,4)

print(a)
a.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([2, 4])

In [33]:
# reshaping tensor using reshape function
b = a.reshape(1,8)

print(b)
b.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([1, 8])

In [34]:
# sum of values in tensor
print(a.sum())

tensor(1.1913)


In [35]:
# average of values in tensor
print(torch.mean(a))

tensor(0.1489)


In [36]:
## 4. Converting NumPy arrays to PyTorch tensors 

In [37]:
# importing numpy library
import numpy as np

# initializing a numpy array
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [38]:
type(a)

numpy.ndarray

In [39]:
# converting the numpy array to tensor
array_to_tensor = torch.from_numpy(a)
print(array_to_tensor)

tensor([[1, 2],
        [3, 4]])


In [40]:
type(array_to_tensor)

torch.Tensor

In [41]:
## 5. Converting PyTorch tensors to NumPy arrays 

In [42]:
# initializing a pytorch tensor
a = torch.tensor([[1,2],[3,4]])
print(a)

type(a)

tensor([[1, 2],
        [3, 4]])


torch.Tensor

In [43]:
# converting pytorch tensor to numpy array
tensor_to_array = a.numpy()
print(tensor_to_array)

type(tensor_to_array)

[[1 2]
 [3 4]]


numpy.ndarray

In [44]:
## 6. Using tensors on GPU

In [45]:
# checking if GPU is available
if torch.cuda.is_available():
  print('GPU is available')
else:
  print('GPU is not available')

GPU is not available


In [51]:
!pip install torch torchvision 
# sending the tensors to GPU
import torch

# Creating tensors directly on the CPU
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[1, 2], [3, 4]])

# Performing the operation on the CPU
c = a + b
print(c)


tensor([[2, 4],
        [6, 8]])
